os: linux
dist: bionic
language: cpp
compiler: 
    - g++
    - clang++

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt install meson ninja
    - sudo apt install libglew-dev libglfw3-dev libglm-dev libyaml-cpp-dev 

script:
    - meson build && ninja -j8 -C build
    #- ninja -j8 -C build test -v
