dist: focal
group: travis_latest
os: linux

language: 
    - cpp

compiler: 
   - gcc

branches:
    only:
        - master
        - develop

before_install:
    - sudo apt-get update -qq

install:
    - sudo pip install 'meson>=0.56' ninja --force-reinstall
    - sudo apt-get -y install libglew-dev libglfw3-dev libglm-dev 

script:
    - meson builddir
    - meson compile -C builddir
    #- meson test -C builddir
    #- meson build && ninja -j8 -C build
    #- ninja -j8 -C build test -v
