os: linux
dist: focal
language: cpp
compiler: 
    - g++
    - clang++

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt install meson 
    - sudo apt install ninja-build
    - sudo apt install libglew-dev libglfw3-dev libglm-dev libyaml-cpp-dev 

script:
    - meson build && ninja -j8 -C build
    #- ninja -j8 -C build test -v
