dist: focal
group: travis_latest
os: linux
language: 
    - python
    - cpp

matrix:
  include:
    - env: CC=g++
    - env: CC=clang

before_install:
    - sudo apt-get update -qq

install:
    - sudo pip install meson ninja
    - sudo apt install libglew-dev libglfw3-dev libglm-dev 

script:
    - meson builddir
    - meson compile -C builddir
    - meson test -C builddir
    #- meson build && ninja -j8 -C build
    #- ninja -j8 -C build test -v
