language: cpp
compiler: 
    - gcc
    - clang

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq apt-transport-https
    - echo "deb https://kdudka.fedorapeople.org/csbuild trusty contrib" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq -y --force-yes csbuild
    - sudo apt-get install libglew-dev libglfw3-dev libglm-dev

script:
    - test -z "$TRAVIS_COMMIT_RANGE" || csbuild --git-commit-range "$TRAVIS_COMMIT_RANGE" -c "meson .. && ninja" --git-bisect
